### ISSUE TITLE
apps.confg 파일은 어디서 찾나요?

### ISSUE THREAD

**Issue by gyyeon** [TechOrgg/ai_speaker4_watson#6]

**Comment by Choi-Eui-Shin** [comment]
ai4w/resources 폴더에 있습니다.

2018-07-31 23:28 GMT+09:00 gyyeon <notifications@github.com>:

**Comment by gyyeon** [comment]
ai4w폴더가 라즈베리파이에 원래 깔려 있는건가요?

**Comment by Choi-Eui-Shin** [comment]
라즈베리에서 제공하는 이미지에는 ai4w 폴더가 없습니다.
하지만 제가 제공하는 이미지에는 이 폴더가 있습니다.
이미지와 관련된 내용은 문서를 참고하세요
