### ISSUE TITLE
혹시!!  사용된 PCB의 설계파일과 거버파일 공유 가능할까요?

### ISSUE THREAD

**Issue by skyu74** [TechOrgg/ai_speaker4_watson#8]
혹시!!  사용된 PCB의 설계파일과 거버파일 공유 가능할까요?

해외에 보니깐 저렴하게 PCB 제작하는곳이 많아서 PCB제작해서 만들어보고 싶어서요?

공유가 가능하시면 skyu74@gmail.com 부탁 드립니다.

감사 합니다.

**Comment by Choi-Eui-Shin** [comment]
한글 TTS 관련된 내용의 테스트가 끝나면 git에 공유 하려 합니다.
그리고 거버 파일은 위 메일로 보내드리겠습니다.

**Comment by skyu74** [comment]
혹시!! 거바파일 보내셨나요?

메일이 안와서요?

**Comment by Choi-Eui-Shin** [comment]
PCB 제작에 사용한 거버 파일 공유합니다.
